version: "3.9"
services:
  supporters:
    build: .
    volumes: 
      - .:/usr/src/app
      - /dev/null:/usr/src/app/Gemfile.lock
    command: sh -c "bin/rails db:migrate RAILS_ENV=development && bundle exec rake db:seed && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"