version: "3.9"
services:
  supporters:
    build: .
    volumes: 
      - .:/usr/src/app
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"